image: node:latest

cache:
  paths:
  - node_modules/

pages:
  stage: deploy
  script:
   - npm install
   - npm run build
   - mkdir public
   - mv index.html public
   - mv src/css/* public/src/css
   - mv bundle.js public
  artifacts:
    paths:
    - public
  only:
  - master